export const Dbas = {
  frameName: 'frame19536',
  frameCommen: 'Frame para exibir frases xpto',
  frameComment: 'Frame para exibir frases xpto',
  frameBackgroundColor: '#FFFFFF',
  imagem: 'https://dummyimage.com/600x400/000/fff',
  imagemLink: 'www.romulo.blog.br',
  title: 'Lorem ipsum dolor sit amet',
  titleAlign: 'left',
  titleFont: 'Poppins',
  titleWeight: '700',
  titleSize: '56px',
  titleColor: '#0b182F',
  description: [
    {
      text: '1 - Ipsum, consectetur adipiscing elit, sed do eiusmod tempor.',
      Font: 'Open Sans',
      Weight: '400',
      Size: '20px',
      Color: '#4D4D4D',
    },
    {
      text: '2 - incididunt ut dolore magna aliqua. Ut enim ad ',
      Font: 'Open Sans',
      Weight: '400',
      Size: '20px',
      Color: 'RED',
    },
    {
      text: '3 -Lorem ipsum dolor sit, consectetur ',
      Font: 'Open Sans',
      Weight: '400',
      Size: '20px',
      Color: '#4D4D4D',
    },
    {
      text: '4 - Lorem ipsum dolor sit amet, ',
      Font: 'Open Sans',
      Weight: '400',
      Size: '20px',
      Color: '#4D4D4D',
    },
  ],
  ButtonText: 'Inscreva-se',
  ButtonTextFontFamily: 'Open Sans',
  ButtonTextFontStyle: 'normal',
  ButtonTextFontSize: '16px',
  ButtonTextFontColor: '#FFFFFF',
  ButtonTextAlign: 'Center',
  ButtonSize: '16px',
  ButtonBackground: '#EE015E',
  ButtonBorder: '1px solid #EE015E',
  ButtonRadius: '8px',
  ButtonLink: 'www.romulo.blog.br',
};
